[colors.primary]
background = '#2B2D30'
foreground = '#DFE1E5'

[colors.normal]
black   = '#1E2022'
red     = '#BC3F3C'
green   = '#4E8052'
yellow  = '#B3AE60'
blue    = '#3975F1'
magenta = '#C77DBB'
cyan    = '#56A8F5'
white   = '#E5E9F0'

[colors.bright]
black   = '#909399'

