# https://alacritty.org/config-alacritty-bindings.html

# MacOS only
# Disable Quit
[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "ReceiveChar"

# Disable select tabs
[[keyboard.bindings]]
key = "1"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "2"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "3"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "4"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "5"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "6"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "7"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "8"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "9"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "0"
mods = "Command"
action = "ReceiveChar"
