add_newline = false
palette = "darkula_dark"
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$cmd_duration
$character"""

[os]
format = "[$symbol ]($style)"
style = "icon"
disabled = false

[directory]
style = "gray"
truncate_to_repo = false
truncation_symbol = '…/'
read_only = " "
read_only_style = "gray"

[fill]
style = "separator"
symbol = "─"

[character]
success_symbol = "[](green)"
error_symbol = "[✗](red)"
vimcmd_symbol = "[](green)"
vimcmd_replace_one_symbol = "[](blue)"
vimcmd_replace_symbol = "[](blue)"
vimcmd_visual_symbol = "[](blue)"

[git_branch]
format = "[$symbol$branch(:$remote_branch) ]($style)"
symbol = " "
style = "gray"

[git_status]
style = "gray"

[package]
symbol = "󰏗 "
disabled = true

[cmd_duration]
format = "[$duration]($style)"
style = "gray"

[palettes.darkula_dark]
icon = "#CED0D6"
separator = "#393B40"
blue = "#3975F1"
gray = "#6F737A"
green = "#4E8052"
red = "#C55554"

# Configuration below was generated by Nerd Font Symbols Preset
# https://starship.rs/presets/nerd-font
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
