[[cmp.prepend_keymap]]
desc = "Next item"
on   = "<C-j>"
run  = "arrow next"

[[cmp.prepend_keymap]]
desc = "Previous item"
on   = "<C-k>"
run  = "arrow prev"

# Plugins
[[mgr.prepend_keymap]]
desc = "run lazygit"
on   = [ "g", "i" ]
run  = "plugin lazygit"
