theme = "darcula"

[editor]
cursorline = true
rulers = [120]
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-modification-indicator", "file-name"]
center = ["diagnostics"]
right = ["file-encoding", "file-line-ending", "file-type", "position-percentage", "position"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
character = "│"
render = true
skip-levels = 1
