#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]
cwd = { fg = "#6F737A" }
border_style = { fg = "#393B41" }
hovered = { bg = "#2E436E" }

[filetype]
rules = [
  { name = "*/", fg = "#DFE1E5" },
]

[input]
border = { fg = "#393B41", bg = "#1E1F22" }
title = { fg = "#DFE1E5" }

[cmp]
border = { fg = "#393B41", bg = "#1E1F22" }
active = { bg = "#2E436E" }
icon_folder = ""

[tasks]
border = { fg = "#393B41", bg = "#1E1F22" }
title = { fg = "#DFE1E5" }

[which]
mask = { bg = "#2B2D30" }
cand = { fg = "#6F737A" }
desc = { fg = "#BCBEC4" }
separator_style = { fg = "#6F737A" }

[confirm]
title = { fg = "#DFE1E5" }
border = { fg = "#393B41", bg = "#1E1F22" }

[spot]
title = { fg = "#DFE1E5" }
border = { fg = "#393B41", bg = "#1E1F22" }
tbl_col = { fg = "#7A7E85" }
tbl_cell = { bg = "#2E436E" }

[notify]
title_info = { fg = "#3592C4" }
title_warn = { fg = "#F2C55C" }
title_error = { fg = "#FA6675" }
icon_info = ""
icon_warn = ""
icon_error = ""

[icon]
prepend_dirs = [
  { name = ".config", text = "󱂀" },
  { name = ".git", text = "󰊢" },
]
prepend_conds = [
  { if = "link", text = "" },
  { if = "dir", text = "" },
]
