# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  nerdFontsVersion: "3"
  showRandomTip: false
  showPanelJumps: true
  spinner:
    frames:
      - '⣾'
      - '⣽'
      - '⣻'
      - '⢿'
      - '⡿'
      - '⣟'
      - '⣯'
      - '⣷'
    rate: 90
git: 
  paging:
    colorArg: "always"
    pager: "delta --paging=never"
  branchLogCmd: "git log --color=always --date=format-local:'%d%.%m.%Y, %H:%M' --graph --format=format:'%C(white)%<(70,trunc)%s%C(reset) %C(cyan)%<(18,trunc)%an%C(reset)  %cd  %C(yellow)%h%C(reset)'"
  parseEmoji: true
notARepository: "quit"
